// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcXyOxeDwR0LWSvlJvHvTDVa1QYMJAyeI',
    appId: '1:400661823654:web:fc178c8225b5d936b87467',
    messagingSenderId: '400661823654',
    projectId: 'plant-6d200',
    authDomain: 'plant-6d200.firebaseapp.com',
    storageBucket: 'plant-6d200.firebasestorage.app',
    measurementId: 'G-MCJ60NR6Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6FYjHYr0KQ7Mg8f99avt5lPx0r4gGb2c',
    appId: '1:400661823654:android:00ea3ff21251769cb87467',
    messagingSenderId: '400661823654',
    projectId: 'plant-6d200',
    storageBucket: 'plant-6d200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy98Q_xSY3-_uSYYYTZecFjiXldTnN56A',
    appId: '1:400661823654:ios:abc136cc7b81eb5fb87467',
    messagingSenderId: '400661823654',
    projectId: 'plant-6d200',
    storageBucket: 'plant-6d200.firebasestorage.app',
    iosBundleId: 'com.example.plantCommunityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy98Q_xSY3-_uSYYYTZecFjiXldTnN56A',
    appId: '1:400661823654:ios:abc136cc7b81eb5fb87467',
    messagingSenderId: '400661823654',
    projectId: 'plant-6d200',
    storageBucket: 'plant-6d200.firebasestorage.app',
    iosBundleId: 'com.example.plantCommunityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcXyOxeDwR0LWSvlJvHvTDVa1QYMJAyeI',
    appId: '1:400661823654:web:41ca5d12284ef15fb87467',
    messagingSenderId: '400661823654',
    projectId: 'plant-6d200',
    authDomain: 'plant-6d200.firebaseapp.com',
    storageBucket: 'plant-6d200.firebasestorage.app',
    measurementId: 'G-DBLLJ32H6T',
  );
}
